### ISSUE TITLE
Wish for your help

### ISSUE THREAD

**Issue by achiless123** [changwoolee/lenet5_hls#10]
Hi @changwoolee ，I‘m VERY interested in your project, you've got a brilliant acheivement.
I also got a zynq-7020 board. But I am a newcomer in this area.
May you tell me how to run your projcet on the board.(in steps)
I'll really appreciate it.
Thanks in advance.

**Comment by changwoolee** [comment]
Hello @achiless123 .

You can set the project by using Xilinx SDSoC or SDx IDE. I used SDSoC 2016.4 version.

First, make the new project for your testing board and import the filesystem except Win10 Test App Release & Win10 Test App/*.

Second, set the hardware function  CONVOLUTION_ LAYER_ 1, CONVOLUTION_ LAYER_ 2, and CONVOLUTION_ LAYER_ 3 in lenet5/hw_layers/image_convolution.cpp as Top Hardware Functions at SDSoC.

Third, set the clock frequency as 100Hz for each hardware functions.

Now you can generate a bitstream file.

Additional information is included in https://github.com/changwoolee/lenet5_hls/issues/9

Thanks and have a nice day :)

**Comment by achiless123** [comment]
Hi, @changwoolee 
thanks for your adivice
more questions ：
How to use the app on win10
i just followed your introduction on readme.md  but i'm puzzlesd
where may i use the instuction ran .elf and ifconfig
on the ubantu system on the zynq7020 arm?
by the way, i tried to find the .elf file but i failed
thanks for your attention.

**Comment by wxbbuaa2011** [comment]
I also need to implement this project, but tried hard and failed several times, so I don't know what to do now. Can I help me? thank you very much.
