### ISSUE TITLE
Unable to open the win 10 test application

### ISSUE THREAD

**Issue by manishtanwar** [changwoolee/lenet5_hls#6]
I am unable to open the win 10 test application. And there are too many .exe files named LeNet5 Test, so could you please tell me the specific directory of the executable file which we are supposed to run for the testing.

**Comment by changwoolee** [comment]
Hi manishtanwar, I'm sorry for the messy upload. The test application is written in UWP(Universial Windows Platform) environment, and I didn't prepare the release build. For now, please open the win 10 test app project with Visual Studio, and run it on there. I'll prepare the release file for the app. Thank you.

**Comment by manishtanwar** [comment]
Could you please tell me the specific directory of the executable file which we are supposed to run for the testing?

**Comment by changwoolee** [comment]
I just uploaded the release package on Win10 Test App Release.  If you want to run the app on VS, open VS by double clicking the LeNet5 Test.sln and press "Run" Button or press F5 on keyboard. I hope the release package will help you.

**Comment by manishtanwar** [comment]
Thank You so much.
